server:
  port: 10086 # eureka服务端口
# 服务注册
spring:
  application: # eureka自己也是一个微服务，需要注册自己到eureka上
    name: eurekaserver # eureka服务名称
eureka:
  client:
    service-url: # eureka服务地址
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients:
      - userservice
      - orderservice